routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Backend\Role\RoleController;
use App\Http\Controllers\Backend\Permission\PermissionController;
use App\Http\Controllers\Backend\Master\MasterController;
use App\Http\Controllers\Backend\ModuleController;
use App\Http\Controllers\Backend\SoftwareversionController;
use App\Http\Controllers\Backend\Model\ModelController;
use App\Http\Controllers\Backend\AjaxController;
use App\Http\Controllers\Backend\Level\LevelController;
use App\Http\Controllers\Backend\Complaint\ComplaintController;
use App\Http\Controllers\Backend\Accessories\AccessoriesController;
use App\Http\Controllers\Backend\CurrencyController;
use App\Http\Controllers\Backend\CountryController;
use App\Http\Controllers\Backend\Device\DeviceController;
use App\Http\Controllers\Backend\Sales\SalesController;
use App\Http\Controllers\Backend\BranchController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\InvoiceController;
use App\Http\Controllers\Backend\SpareController;
use App\Http\Controllers\Backend\Sales\ActivationController;
use App\Http\Controllers\Backend\Sales\SalesReturnController;
use App\Http\Controllers\Backend\Sales\SalesRequestController;
use App\Http\Controllers\Backend\Stock\StockController;
use App\Http\Controllers\Backend\Stock\TransferController;
use App\Http\Controllers\Backend\Stock\PurchaseRequestController;
use App\Http\Controllers\Backend\ServiceController;
use App\Http\Controllers\Backend\WarrantyController;
use App\Http\Controllers\Backend\Transfer\IMEITransferController;
use App\Http\Controllers\Backend\ServiceTransferController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\SpareSaleController;
use App\Http\Controllers\Backend\FAQController;
use App\Http\Controllers\Backend\DOAController;
use App\Http\Controllers\Backend\StockServiceController;
use App\Http\Controllers\Backend\ReportController;
use App\Http\Controllers\Backend\LevelRateController;
use App\Http\Controllers\Backend\ChangePasswordController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\Backend\BomController;
use App\Http\Controllers\Backend\SoftwareController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/complete-registration', [HomeController::class, 'completeRegistration'])->name('complete.registration');

Route::get('/google_auth', [HomeController::class, 'googleAuthRegistration'])->name('google.auth');

// Route::group(['middleware' => 'auth'], function () {
Route::middleware(['auth', '2fa'])->group(function () {
    Route::post('/2fa', function () {
        return redirect(route('dashboard'));
    })->name('2fa');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
    Route::get('change-password', [ChangePasswordController::class, 'index']);
    Route::post('change-password', [ChangePasswordController::class, 'store'])->name('change.password');
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');
    // Route::group(['middleware' => ['AdminAccess:settings|user_access']], function () {
    //
    // });
    Route::group(['middleware' => ['AdminAccess']], function () {
        Route::group(['prefix' => 'admin'], function () {
            Route::group(['middleware' => ['AdminAccess:settings']], function () {
                Route::group(['prefix' => 'master/{table}'], function () {
                    Route::get('index', [MasterController::class, 'index']);
                    Route::get('create/{id?}', [MasterController::class, 'create']);
                    Route::post('store/{id?}', [MasterController::class, 'store']);
                    Route::post('getData', [MasterController::class, 'getMasterData']);
                });
                Route::group(['prefix' => 'settings'], function () {
                    Route::resource('currency', CurrencyController::class);
                    Route::post('currency/get', [CurrencyController::class, 'getCurrency'])->name('currency.get');
                    Route::resource('country', CountryController::class);
                    Route::post('country/get', [CountryController::class, 'getCountry'])->name('country.get');
                    Route::resource('branch', BranchController::class);
                    Route::post('branch/get', [BranchController::class, 'getBranchList'])->name('branch.get');
                    Route::resource('softwareversion', SoftwareversionController::class);
                    Route::post('softwareversion/get', [SoftwareversionController::class, 'getSoftwareVersion'])->name('softwareversion.get');
                    Route::resource('spare', SpareController::class, ['except' => ['show']]);
                    Route::post('spare/get', [SpareController::class, 'getSpare'])->name('spare.get');
                    Route::get('spare/import', [SpareController::class, 'import'])->name('spare.import');
                    Route::post('spare/import', [SpareController::class, 'import_store'])->name('spare.import_store');
                    //FAQ
                    Route::resource('faqs', FAQController::class);
                    Route::post('faqs/get', [FAQController::class, 'getFAQData'])->name('faq.get');

                });


                Route::post('level/get', [LevelController::class, 'getLevelData'])->name('level.get');
                Route::resource('level', LevelController::class, ['except' => ['show']]);

                Route::post('level/rate/get', [LevelRateController::class, 'getLevelRateData'])->name('level.rate.get');
                Route::resource('level/rate', LevelRateController::class, ['except' => ['show'] ,'names' => 'level.rate']);


                Route::resource('complaint', ComplaintController::class, ['except' => ['show']]);
                Route::post('complaint/get', [ComplaintController::class, 'getComplaintData'])->name('complaint.get');
                Route::get('complaint/import', [ComplaintController::class, 'import'])->name('complaint.import');
                Route::post('complaint/import', [ComplaintController::class, 'import_store'])->name('complaint.import_store');

                Route::resource('accessories', AccessoriesController::class, ['except' => ['show']]);
                Route::post('accessories/get', [AccessoriesController::class, 'getAccessoriesData'])->name('accessories.get');

                Route::resource('model', ModelController::class, ['except' => ['show']]);
                Route::get('model/specification/{id}', [ModelController::class, 'getModelSpecifications'])->name('model.specification');
                Route::post('model/delete/{id}', [ModelController::class, 'destroy'])->name('model.destroy');
                Route::post('model/get', [ModelController::class, 'getModelData'])->name('model.get');
            });
            Route::group(['middleware' => ['AdminAccess:user_access']], function () {
                Route::get('module/create', [ModuleController::class, 'create'])->name('module.create');
                Route::get('module', [ModuleController::class, 'index'])->name('module');
                Route::get('permission/create', [PermissionController::class, 'create'])->name('permission.create');
                Route::get('permission', [PermissionController::class, 'index'])->name('permission');
                Route::get('role/create', [RoleController::class, 'create'])->name('role.create');
                Route::get('role', [RoleController::class, 'index'])->name('role');
                Route::get('user/create', [UserController::class, 'create'])->name('user.create');
                Route::get('user', [UserController::class, 'index'])->name('user');
                Route::get('user/{id}/password/change', [UserController::class, 'changePassword'])->name('user.password.change');
                Route::PATCH('user/{id}/password/change', [UserController::class, 'updatePassword'])->name('user.password.update');
            });


            Route::resource('module', ModuleController::class, ['except' => ['create', 'index']]);
            Route::post('module/get', [ModuleController::class, 'getModule'])->name('module.get');
            Route::resource('role', RoleController::class, ['except' => ['show', 'create', 'index']]);
            Route::post('role/get', [RoleController::class, 'getRole'])->name('role.get');
            Route::post('role/getpermission', [RoleController::class, 'getPermissions'])->name('role.get.permission');
            Route::resource('permission', PermissionController::class, ['except' => ['show', 'create', 'index']]);
            Route::post('permission/get', [PermissionController::class, 'getPermissionList'])->name('permission.get');
            Route::resource('user', UserController::class, ['except' => ['show', 'create', 'index']]);
            Route::post('user/get', [UserController::class, 'getUser'])->name('user.get');
            Route::get('user/varifyemail', [UserController::class, 'varifyemail']);
            Route::get('user/varifycontact', [UserController::class, 'varifycontact']);
            Route::get('user/varifyusername', [UserController::class, 'varifyusername']);
            Route::get('generate/invoice', [InvoiceController::class, 'generateInvoicePDF'])->name('generate.invoice.pdf');
            Route::get('generate/service', [InvoiceController::class, 'generateServicePDF'])->name('generate.service.pdf');
            /* shabi */

app/Models/Accessories.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Accessories extends Model
{
    use HasFactory;

}

app/Models/AppealComment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AppealComment extends Model
{
    use HasFactory;
    protected $table = 'appeal_rel_comments';
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/BaseModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    /**
     * Generate drop-down select data with basic IDs.
     *
     * @param string $field_name
     *
     * @return array
     */
    public static function getSelectData($field_name = 'name')
    {
        $collection = parent::all();

        return self::getItems($collection, $field_name);
    }

    /**
     * Generate items for drop-down select data with basic IDs.
     *
     * @param $collection
     * @param string $field_name
     *
     * @return array
     */
    public static function getItems($collection, $field_name)
    {
        $items = [];

        foreach ($collection as $model) {
            $items[$model->id] = [
                'id' => $model->id,
                'name' => $model->$field_name,
                'model' => $model,
            ];
        }

        foreach ($items as $id => $item) {
            $items[$item['id']] = $item['name'];
        }

        return $items;
    }
}

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
}

app/Models/Complaint.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Complaint extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/CustomerSale.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class CustomerSale extends Model
{
    use HasFactory;
    protected $table = "customer_sales";  
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/Doa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Doa extends Model
{
    use HasFactory;
    protected $table = "doa";  
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/IMEI.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class IMEI extends Model
{
    use HasFactory;
    protected $table = "imei";  
    protected $guarded = array();
}

app/Models/IMEIDetails.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class IMEIDetails extends Model
{
    use HasFactory;
    protected $table = "imei_details";  
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/IMEITransfer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class IMEITransfer extends Model
{
    use HasFactory;
    protected $table = "imei_transfer";  
    protected $guarded = array();
}

app/Models/IMEITransferItems.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class IMEITransferItems extends Model
{
    use HasFactory;
    protected $table = "imei_transfer_items";  
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/InvoiceFile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InvoiceFile extends Model
{
    use HasFactory;
    protected $table = 'invoice_file';
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/Level.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    use HasFactory;
    protected $table = 'levels';
}

app/Models/LevelRate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LevelRate extends Model
{
    use HasFactory;
    protected $table = 'level_rate';
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/ModelDetails.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ModelDetails extends Model
{
    use HasFactory;
    protected $table = 'variant_details';
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/Models.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Models extends Model
{
    use HasFactory;
    protected $table = 'models';
}

app/Models/ServiceFile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ServiceFile extends Model
{
    use HasFactory;
    protected $table = 'service_image';
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/Spare.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Spare extends Model
{
    use HasFactory;
    protected $table = "spare";  
    public $timestamps = false;
    protected $guarded = array();
}

app/Models/Traits/ModelAttributes.php
<?php

namespace App\Models\Traits;

trait ModelAttributes
{
    /**
     * @return string
     */
    public function getEditButtonAttribute($permission, $route)
    {
        //if (access()->allow($permission)) {
            return '<a href="'.route($route, $this).'" data-toggle="tooltip" data-placement="top" title="Edit" class="btn btn-primary btn-sm">
                    <i class="feather icon-edit"></i>
                    </a>';
        //}
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute($permission, $route)
    {
        // if (access()->allow($permission)) {
            return '<a href="'.route($route, $this).'" 
                    class="btn btn-primary btn-danger btn-sm" 
                    data-method="delete"
                    data-trans-button-cancel="Cancel"
                    data-trans-button-confirm="Delete"
                    data-trans-title="Are you sure you want to do this?">
                        <i data-toggle="tooltip" data-placement="top" title="Delete" class="feather icon-trash"></i>
                </a>';
        //}
    }
}

app/Models/Traits/Uuid.php
<?php

namespace App\Models\Traits;

use Ramsey\Uuid\Uuid as PackageUuid;

/**
 * Trait Uuid.
 */
trait Uuid
{
    /**
     * @param $query
     * @param $uuid
     *
     * @return mixed
     */
    public function scopeUuid($query, $uuid)
    {
        return $query->where($this->getUuidName(), $uuid);
    }

    /**
     * @return string
     */
    public function getUuidName()
    {
        return property_exists($this, 'uuidName') ? $this->uuidName : 'uuid';
    }

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->{$model->getUuidName()} = PackageUuid::uuid4()->toString();
        });
    }
}

resources/views/admin/model/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="main-panel">
        <div class="panel-hedding">
            <div class="row mb-4">
                <div class="col-md-6">
                   <h4 class="card-title-text">{{((isset($edit_model)) ? "Edit":'Create')}} Model</h4>
                </div>
                <div class="col-md-6">
                    <div class="add-new">
                        <a class="btn btn-primary" href="{{ url('admin/model') }}"> <i
                            class="feather icon-list"></i> Model List</a>
                    </div>
                </div>
            </div>
            @include('inc.alert')
            @if (isset($edit_id))
                {{ Form::model($edit_model, ['route' => ['model.update', $edit_id],'class' => 'form-horizontal','role' => 'form','method' => 'PATCH','id' => 'create-model']) }}
            @else
                {{ Form::open(['route' => 'model.store','class' => 'form-horizontal','role' => 'form','method' => 'POST','id' => 'create-model']) }}
            @endif
            @csrf
            
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ Form::label('name', __('Brand')) }}
                    {{ Form::select('brand_id', $brand, old('brand_id',(isset($edit_model)) ? $edit_model->brand_id:''), ['class' => 'form-control js-example-basic-single', 'placeholder' => 'Select Brand', 'required' => 'required']) }}
                </div>
                <div class="form-group col-md-6">
                    {{ Form::label('name', __('Device')) }}
                    {{ Form::select('device_id', $device, old('device_id',(isset($edit_model)) ? $edit_model->device_id:''), ['class' => 'form-control js-example-basic-single', 'placeholder' => 'Select Device', 'required' => 'required']) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('name', __('Model Name')) }}
                    {{ Form::text('name', old('name',(isset($edit_model)) ? $edit_model->name:''), ['class' => 'form-control', 'required' => 'required']) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('name', __('Factory Name')) }}
                    {{ Form::text('factory_name', old('factory_name',(isset($edit_model)) ? $edit_model->factory_name:''), ['class' => 'form-control', 'required' => 'required']) }}
                </div>
                @php
                $selected = [];
                if (isset($edit_model)) {
                    $selected = explode(',',$edit_model->country_id);
                }
                @endphp
                <div class="form-group col-md-4">
                    {{ Form::label('name', __('Country')) }}
                    <select name="country_id[]" multiple="multiple" class="js-example-basic-multiple select2-hidden-accessible" id="country_id">
                        @foreach($country as $k => $v)
                            <option value="{{ $k }}" {{ (in_array($k, $selected)) ? 'selected' : '' }}>{{ $v}}</option>
                        @endforeach
                    </select>
                </div>
                <table class="table table-bordered" id="dynamicTable">  
                <thead>
                <tr>
                    <th>Color</th>
                    <th>RAM</th>
                    <th>ROM</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @if(isset($edit_model_details))
                  @foreach($edit_model_details as $k =>$v)
                 
                    <tr>
                        <td>
                         <select  class="form-control js-example-basic-single" name="addmore[{{ ++$k }}][color_id]" required="required">@foreach ($color as $key => $value)<option value="{{ $key }}" @if($v->color_id == $key) selected @endif>{{ $value }}</option>@endforeach</select></td>
                        </td>
                        <td>
                         <select  class="form-control js-example-basic-single" name="addmore[{{ $k }}][ram_id]"><option value="">--select--</option>@foreach ($ram as $key => $value)<option value="{{ $key }}" @if($v->ram_id == $key) selected @endif>{{ $value }}</option>@endforeach</select>
                        </td>
                        <td>
                         <select  class="form-control js-example-basic-single" name="addmore[{{ $k }}][rom_id]"><option value="">--select--</option>@foreach ($rom as $key => $value)<option value="{{ $key }}" @if($v->rom_id == $key) selected @endif>{{ $value }}</option>@endforeach</select>
                         <input value="{{(isset($edit_model_details)) ? $v->id:'0'}}" name="addmore[{{ $k }}][model_id]" type="hidden">
                        </td>
                        <td>
                            
                            @if ($k == 1)
                            <button type="button" name="add" id="add" class="btn btn-success">Add</button> 
                            @else
                            <a href="{{ route('model.destroy', $v->id) }}" data-method="delete" class="btn btn-danger">Remove</a>
                            @endif
                        </td>
                    </tr>
                  @endforeach
                @endif
               </tbody>
              
              </table> 
            </div>
            
            <button type="submit" class="btn btn-success float-right">Submit</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection
@section('pagescript')
<script src="{{ asset('js/select2/select2.min.js')}}"></script>
<script src="{{ asset('js/select2/bloodhound.min.js')}}"></script>
<script type="text/javascript">
$(document).ready(function(){
   var count =  $('#dynamicTable tbody tr').length;
   if(count == 0) dynamic_field(count);
    
    function dynamic_field(number)
    {
        html = '<tr>';
        html += '<td><select  class="form-control js-example-basic-single select2" name="addmore[' + number + '][color_id]" required="required"><option value="">--select--</option>@foreach ($color as $key => $value)<option value="{{ $key }}">{{ $value }}</option>@endforeach</select></td>';
        html += '<td><select  class="form-control js-example-basic-single select2" name="addmore[' + number + '][ram_id]" ><option value="">--select--</option>@foreach ($ram as $key => $value)<option value="{{ $key }}">{{ $value }}</option>@endforeach</select></td>';
        html += '<td><select  class="form-control js-example-basic-single select2" name="addmore[' + number + '][rom_id]" ><option value="">--select--</option>@foreach ($rom as $key => $value)<option value="{{ $key }}">{{ $value }}</option>@endforeach</select><input value="0" name="addmore[' + number + '][model_id]" type="hidden"></td>';
        
        if(number > 0)
        { 
            html += '<td><button type="button" name="remove" id="" class="btn btn-danger remove">Remove</button></td></tr>';
            $('tbody').append(html);
        }
        else
        { 
            html += '<td><button type="button" name="add" id="add" class="btn btn-success">Add</button></td></tr>';
            $('tbody').append(html);
        }
        $(".js-example-basic-single").select2({
            placeholder: "--select--",
        });
    }

    $(document).on('click', '#add', function(){
        count++;
        dynamic_field(count);
    });
    $(document).on('click', '.remove', function(){
        //count--;
        $(this).closest("tr").remove();
    });
});

</script>
@endsection

resources/views/admin/model/index.blade.php
@extends('layouts.app')

@section('content')
<div class="main-panel">
    <div class="panel-hedding">
        <div class="row mb-4">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
                <div class="add-new">
                    <a class="btn btn-primary" href="{{ route('model.create') }}"> <i class="feather icon-plus"></i> Create Model</a>
                </div>
            </div>
        </div>
        <div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-title">
						<div class="card-title-left">
							<h4 class="card-title-text">Model Management</h4>
						</div>
					</div>
				  <div class="card-body">
					  <div class="table-responsive">
				  	<table id="model-table" class="table table-striped table-bordered" data-ajax_url="{{ route("model.get") }}">
					        <thead>
					            <tr>
								    <th width="5">Sl</th>
					                <th>Brand</th>
					                <th>Model</th>
									<th>Factory Name</th>
									<th>Device</th>
									<th  width="100">Specifications</th>
					                <th  width="100">Actions</th>
									<th  width="100">Status</th>
					            </tr>
					        </thead>
					    </table>
					  </div>
					</div>
				</div>
			</div>
		</div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Specifications</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	    <div id="model-data">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

@endsection
@section('pagescript')
@include('inc.datatables-js')
<script>
    FTX.Utils.documentReady(function() {
        FTX.Models.list.init();
    });
	$(document).on('click', '#model-table tbody tr button', function() {
		var $this = $(this);
        id = $this.data("id");
		name = $this.data("name");
		brand = $this.data("brand");
		$.get("model/specification/"+id, function (data) {
           $('#model-data').html(data);
		   $("#exampleModal").modal("show");
		   $('.modal-title').text(name+'('+brand+') Specifications');
		});
    });
</script>
@endsection

resources/views/admin/model/view.blade.php
<table id="modaldata" class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th>Color</th>
            <th>RAM</th>
            <th>ROM</th>
        </tr>
    </thead>
    <tbody>
        @if(isset($model_details))
            @foreach($model_details as $k =>$v)
                <tr>
                  <td>{{$v->color_name}}</td>
                  <td>{{$v->ram_name}}</td>
                  <td>{{$v->rom_name}}</td>
                </tr>
            @endforeach
        @endif
    </tbody>
</table>